### ISSUE TITLE
may I export "LevelSequence" module?

### ISSUE THREAD

**Issue by mirchd** [asqbtcupid/unreal.lua#21]
when I export LevelSequence module, error:
LevelSequenceObject.generated.h can not be found..

**Comment by asqbtcupid** [comment]
yes.

 1. add "LevelSequence" to luaconfig.ini

 2. add "LevelSequence" to LuaPluginRuntime.build.cs 's PublicDependencyModuleNames or PrivateDependencyModuleNames.

 3. You may meet link error for the first time,then make tiny change to your gamemodule.build.cs and compile again.

 4. Then still link error,because "LevelSequence" module dependent on "MovieScene",.So you add MovieScene to  LuaPluginRuntime.build.cs 's PublicDependencyModuleNames or PrivateDependencyModuleNames.


another module is added like this way.

**Comment by mirchd** [comment]
thank you very much.
it is ok
